# Generated by Django 6.0.5 on 2026-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='prefix',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
